### ISSUE TITLE
Webpack 2 support

### ISSUE THREAD

**Issue by yleclanche** [metalabdesign/css-split-webpack-plugin#10]
Hello,

Is this supposed to work with webpack 2 ? I get this : `Error: Cannot find module 'webpack/lib/SourceMapSource`
Not sure if this is a configuration issue or a lack of webpack 2 support.

Thanks.

**Comment by izaakschroeder** [comment]
I need to change this to `import {SourceMapSource} from 'webpack-sources';` for `webpack@2`. 😄 I'll look into it!

**Comment by izaakschroeder** [comment]
Should be available in `+ css-split-webpack-plugin@0.2.2` 🎉

**Comment by yleclanche** [comment]
Nice ! Thanks

**Comment by izaakschroeder** [comment]
Happy to help! Let me know if anything else shows up. 🙏

**Comment by yleclanche** [comment]
I tried your fix today and it's not working.
There is another import issue : `Error: Cannot find module 'webpack/lib/RawSource'`
Importing RawSource from webpack-sources resolve the import error but it crashed during the build : http://pastie.org/10977708
