### ISSUE TITLE
Webpack 2 support - part 2

### ISSUE THREAD

**Issue by yleclanche** [metalabdesign/css-split-webpack-plugin#13]
I tried the 0.2.2 and it's not working with Webpack 2.

There is another import issue : `Error: Cannot find module 'webpack/lib/RawSource'`
Importing RawSource from webpack-sources resolve the import error but it crashed during the webpack build : http://pastie.org/10977708

**Comment by yleclanche** [comment]
Ok, I made more tests and my issue is not related to webpack 2 (except for the import issue).
This fixes the other issue : https://github.com/metalabdesign/css-split-webpack-plugin/pull/9

**Comment by izaakschroeder** [comment]
Sorry for the delay, things have been crazy busy here 😄  I think all should be resolved in `v0.2.3` and the corresponding additional integration tests with `webpack@2` https://github.com/metalabdesign/css-split-webpack-plugin/pull/14 and the merging of https://github.com/metalabdesign/css-split-webpack-plugin/pull/9.

**Comment by izaakschroeder** [comment]
Feel free to re-open this issue if it's still giving you trouble. 🎉
