### ISSUE TITLE
Source maps not working with less

### ISSUE THREAD

**Issue by kfeinUI** [metalabdesign/css-split-webpack-plugin#4]
I load in less like so
`{
			test: /\.(less|css)$/,
			loader: ExtractTextPlugin.extract('css?-url&-autoprefixer&sourceMap!less?sourceMap')
		}`
with plugins
`new ExtractTextPlugin('[name].css'),
		new CSSSplitWebpackPlugin({ //IE9 will ignore any more than ~4000 selectors. This does the work for us of splitting into smaller files.
			imports: true,
			preserve: true
		})`

Tried with and without preserve. Even with the preserved sheet, the source map won't load (testing in Chrome). Works fine when I comment out this plugin.

**Comment by izaakschroeder** [comment]
Thanks for the report! Will investigate this. 😄

**Comment by kfeinUI** [comment]
Cool. Let me know if you need anything further from my end. Would be nice to get source maps working for either case, but I'd settle for keeping the preserved flavor for modern browsers (can use conditional comments).

**Comment by izaakschroeder** [comment]
@kfeinUI Resolved here: https://github.com/metalabdesign/css-split-webpack-plugin/pull/6. 😄  Should be merged and published soon.
